### ISSUE TITLE
wh binary not found

### ISSUE THREAD

**Issue by Pipboyguy** [hyperqueryhq/whale-bigquery-public-data#3]
![image](https://user-images.githubusercontent.com/34739235/103029375-5891e500-4562-11eb-9a34-d7aaec0300af.png)

@rsyi

**Comment by rsyi** [comment]
Ah really good catch. Yeah the commands should be reversed: clone into the directory, then install whale, otherwise the clone will overwrite the binary. :) I'll revise the documentation accordingly -- thanks @Pipboyguy! (let me know if it works!)
